import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Plus,Swords,Pencil,Shield,Diamond,Trash2} from 'lucide-react';
import {useApp} from '../lib/AppContext';
import {Button,Empty,PageTitle,Panel,Tag,Modal} from '../components/ui';
import {CharacterEditor,GearEditor} from '../components/Editors';
import {enhancementLabel,slots,type Equipment} from '../domain/types';
import {Onboarding} from '../components/Onboarding';
export function Gear(){
  const a=useApp(),s=a.snapshot;const [edit,setEdit]=useState<Equipment|true|null>(null),[charEdit,setCharEdit]=useState<'new'|'edit'|null>(null),[remove,setRemove]=useState<Equipment|null>(null),[removeChar,setRemoveChar]=useState(false),[initialSlot,setInitialSlot]=useState('');
  if(!s)return null;if(!a.familyId)return <Onboarding/>;
  const chars=s.characters.filter(c=>c.game_profile_id===a.familyId),character=chars.find(c=>c.id===a.characterId),equipped=s.equipment.filter(e=>e.character_id===a.characterId),inventory=s.equipment.filter(e=>e.game_profile_id===a.familyId&&!e.character_id);
  return <><PageTitle eyebrow="CHARACTERS & EQUIPMENT" title="Know where you stand." description="Your real equipment, saved for your next session." action={<Button onClick={()=>{setInitialSlot('');setEdit(true);}} disabled={a.offline}><Plus size={16}/>Add equipment</Button>}/>
    <p><Link className="text-link" to="/reference">Browse gear stats & PvE progression guide →</Link></p>
    <div className="character-tabs">{chars.map(c=><button key={c.id} className={c.id===a.characterId?'selected':''} onClick={()=>a.setCharacterId(c.id)}><span className="mini-emblem"><Swords size={16}/></span><span><strong>{c.name}</strong><small>Lv. {c.level} · {c.class_name}</small></span></button>)}<Button className="secondary" onClick={()=>setCharEdit('new')} disabled={a.offline}><Plus size={16}/>Add character</Button></div>
    {character?<Panel><div className="panel-heading"><div><h2>{character.name}<Tag>{character.playstyle}</Tag></h2><p className="muted">Equipped items · {equipped.length} of {Object.keys(slots).length} slots recorded</p></div><div className="actions"><Button className="secondary small" onClick={()=>setCharEdit('edit')} disabled={a.offline}><Pencil size={14}/>Edit character</Button><button className="icon-button danger-text" aria-label="Remove character" onClick={()=>setRemoveChar(true)} disabled={a.offline}><Trash2 size={16}/></button></div></div>
      <div className="gear-grid">{Object.entries(slots).map(([key,label])=>{const item=equipped.find(e=>e.slot===key);return <button className={'gear-slot '+(item?'filled':'')} key={key} onClick={()=>{setInitialSlot(key);setEdit(item??true);}} disabled={a.offline}><span className="slot-label">{label}</span><span className="slot-art">{key.includes('ring')||key.includes('earring')||key==='necklace'||key==='belt'?<Diamond/>:key.includes('hand')||key==='awakening'?<Swords/>:<Shield/>}{item&&<b>{item.enhancement>15?enhancementLabel(item.enhancement).split(' ')[0]:item.enhancement?'+'+item.enhancement:''}</b>}</span><strong>{item?.name??'Empty slot'}</strong><small>{item?(item.item_key?'Reviewed catalog':'Manual entry'):'Add equipment'}</small></button>;})}</div>
      <p className="subtle-note">Stats are not inferred from custom items. Use your in-game values when assessing upgrades.</p></Panel>:<Panel><Empty title="Meet your first character" action={<Button onClick={()=>setCharEdit('new')}>Add character</Button>}>Create a character to start recording equipment.</Empty></Panel>}
    <Panel><div className="panel-heading"><div><h3>Family equipment inventory</h3><p className="muted">Owned items waiting for their next adventure</p></div><Tag>{inventory.length} items</Tag></div>{inventory.length?<div className="item-list">{inventory.map(e=><div className="material-row" key={e.id}><span className="item-icon"><Diamond size={20}/></span><div><strong>{e.name}</strong><small>{enhancementLabel(e.enhancement)} · {e.item_key?'Reviewed catalog':'Manual entry'}</small></div><Button className="secondary small" onClick={()=>setEdit(e)} disabled={a.offline}>Edit / equip</Button><button className="icon-button" aria-label={'Remove '+e.name} onClick={()=>setRemove(e)} disabled={a.offline}><Trash2 size={16}/></button></div>)}</div>:<div className="quiet-empty">Unequipped items and recorded roadmap rewards appear here.</div>}</Panel>
    {edit&&<GearEditor equipment={edit===true?undefined:edit} initialSlot={initialSlot} onRemove={()=>{if(edit!==true)setRemove(edit);setEdit(null);}} onClose={()=>setEdit(null)}/>}

    {charEdit&&<CharacterEditor character={charEdit==='edit'?character:undefined} onClose={()=>setCharEdit(null)}/>}
    {remove&&<Modal title="Remove owned equipment?" onClose={()=>setRemove(null)}><p>{remove.name} will be removed from your recorded inventory. This does not change the game.</p><Button className="danger" loading={a.pending} onClick={async()=>{if(await a.save('gear_delete',{id:remove.id}))setRemove(null);}}>Remove equipment</Button></Modal>}
    {removeChar&&character&&<Modal title="Remove character?" onClose={()=>setRemoveChar(false)}><p>{character.name} will be removed. Their equipment returns to family inventory, and their goals become family goals.</p><Button className="danger" loading={a.pending} onClick={async()=>{if(await a.save('character_delete',{id:character.id}))setRemoveChar(false);}}>Remove character</Button></Modal>}
  </>;
}
