import {Link} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,Swords,Coins,Route,Clock3,CheckCircle2,Sparkles,Package,Compass} from 'lucide-react';
import {useApp} from '../lib/AppContext';
import {PageTitle,Panel,Tag,Empty} from '../components/ui';
import {goalMissing,orderedSteps,stepReadiness,fmt} from '../domain/roadmap';
import {Onboarding} from '../components/Onboarding';
export function Home(){
  const {snapshot:s,familyId,characterId,setCharacterId}=useApp();if(!s)return null;
  if(!s.game_profiles.length||!s.characters.some(c=>c.game_profile_id===familyId))return <Onboarding/>;
  const character=s.characters.find(c=>c.id===characterId),goals=s.goals.filter(g=>g.game_profile_id===familyId&&g.status==='active');
  const goal=goals[0],steps=goal?orderedSteps(s.steps.filter(x=>x.goal_id===goal.id)):[],next=steps.find(x=>stepReadiness(s,x).ready)??steps.find(x=>x.status!=='completed'),completed=steps.filter(x=>x.status==='completed').length;
  const balance=s.resources.find(r=>r.game_profile_id===familyId&&r.item_key==='silver'),missing=goal?goalMissing(s,goal):[];
  const readiness=next?stepReadiness(s,next):null,events=s.events.filter(e=>e.game_profile_id===familyId).slice(0,4);
  const equipment=s.equipment.filter(e=>e.character_id===characterId).length;
  return <>
    <PageTitle eyebrow="YOUR ADVENTURE AT A GLANCE" title={'Welcome back, '+s.profile.display_name+'.'} description="A little closer to your next chapter." action={<span className="date-label">{new Intl.DateTimeFormat('en',{month:'long',day:'numeric',year:'numeric'}).format(new Date())}</span>}/>
    {s.characters.filter(c=>c.game_profile_id===familyId).length>1&&<label className="home-character-picker"><span>Playing as</span><select aria-label="Active character" value={characterId} onChange={e=>setCharacterId(e.target.value)}>{s.characters.filter(c=>c.game_profile_id===familyId).map(c=><option value={c.id} key={c.id}>{c.name} · {c.class_name}</option>)}</select></label>}
    <div className="overview-grid"><Panel className="journey-hero"><div className="hero-art" aria-hidden="true"><Compass/><div/><i/></div><div className="hero-content"><Tag tone="gold"><Sparkles size={12}/>YOUR NEXT MILESTONE</Tag><h2>{goal?goal.title:'A clear path starts here.'}</h2><p>{next?next.title:'Turn your next upgrade into a few achievable steps. Your goals, materials, and progress will stay together.'}</p><Link className="button" to="/roadmap">{goal?'Continue your roadmap':'Create your first roadmap'}<ArrowRight size={17}/></Link></div>{goal&&<div className="hero-progress"><div><span>JOURNEY PROGRESS</span><strong>{completed}<small> / {steps.length} steps</small></strong></div><progress max={steps.length} value={completed}/><p>{readiness?.ready?'You have what you need for the next step.':completed?'Every completed step brings you closer.':'Set your starting point and take the first step.'}</p></div>}</Panel>
      <Panel className="character-summary"><div className="panel-heading"><span className="eyebrow">ACTIVE CHARACTER</span><Link to="/gear" aria-label="Open character gear"><ArrowUpRight size={19}/></Link></div><div className="character-emblem"><Swords size={36}/></div><h2>{character?.name}</h2><p className="muted">Lv. {character?.level} · {character?.class_name}</p><Tag>{character?.playstyle}</Tag><div className="character-gear-count"><strong>{equipment}</strong><span>equipped items</span><Link to="/gear">Manage gear <ArrowRight size={14}/></Link></div></Panel></div>
    <div className="stat-grid"><Panel className="stat"><div className="stat-icon"><Coins/></div><div><span>Silver on hand</span><strong className="balance-number">{fmt(balance?.quantity??'0')}</strong><small>Manually recorded · family-wide</small></div></Panel><Panel className="stat"><div className="stat-icon"><Route/></div><div><span>Active roadmaps</span><strong>{goals.length.toString().padStart(2,'0')}</strong><small>Your next achievable upgrades</small></div></Panel><Panel className="stat"><div className="stat-icon"><CheckCircle2/></div><div><span>Steps completed</span><strong>{s.steps.filter(x=>s.goals.some(g=>g.id===x.goal_id&&g.game_profile_id===familyId)&&x.status==='completed').length.toString().padStart(2,'0')}</strong><small>Progress worth remembering</small></div></Panel></div>
    <div className="detail-grid"><Panel><div className="panel-heading"><div><h3>Gather for your next chapter</h3><p className="muted">Materials remaining for your priority roadmap</p></div><Link to="/resources" aria-label="Open resources"><ArrowUpRight size={19}/></Link></div>{missing.length?<div className="material-list">{missing.map(m=><div className="material-row" key={m.id}><div className="item-icon"><Package size={19}/></div><div><strong>{m.name}</strong><small>{fmt(m.available)} available · {fmt(m.required)} needed</small></div><Tag tone={m.missing?'gold':'green'}>{m.missing?fmt(m.missing)+' to go':'Ready'}</Tag></div>)}</div>:<div className="quiet-empty"><Package size={24}/><p>Add a roadmap with material requirements to see what to gather.</p></div>}<Link className="panel-link" to="/resources">Manage resources <ArrowRight size={15}/></Link></Panel>
      <Panel><div className="panel-heading"><div><h3>Recent moments</h3><p className="muted">Your journey, recorded</p></div><Clock3 size={19}/></div>{events.length?<div className="activity-list">{events.map(e=><div className="activity" key={e.id}><span className="activity-dot"/><div><p>{e.description}</p><small>{new Date(e.created_at).toLocaleString('en',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></div></div>)}</div>:<Empty title="A fresh page">Your saved changes will appear here.</Empty>}<Link className="panel-link" to="/more?tab=journal">Open journal <ArrowRight size={15}/></Link></Panel></div>
  </>;
}
