import {useState} from 'react';
import ladderDraft from '../data/catalog-ladder-draft.json';
import {Link,useSearchParams} from 'react-router-dom';
import {BookOpen,Settings,Download,ShieldCheck,Trash2,Plus,Pencil,ArrowDownUp,ExternalLink,LogOut} from 'lucide-react';
import {Capacitor} from '@capacitor/core';
import {Browser} from '@capacitor/browser';
import {Directory,Encoding,Filesystem} from '@capacitor/filesystem';
import {Share} from '@capacitor/share';
import {useApp} from '../lib/AppContext';
import {callbackUrl,humanError,isLocal,supabase} from '../lib/client';
import type {Catalog,Family,ProgressEvent,Resource} from '../domain/types';
import {Button,Empty,External,Field,Modal,PageTitle,Panel,SubmitForm,Tag,str} from '../components/ui';
import {FamilyEditor} from '../components/Editors';
import {ResourceEditor} from './Resources';
import {Auth} from './Auth';

export function More(){
  const a=useApp(),s=a.snapshot!,[params,setParams]=useSearchParams(),tab=params.get('tab')??'journal';
  const [event,setEvent]=useState<ProgressEvent|null>(null),[adjust,setAdjust]=useState<Resource|null>(null),[choose,setChoose]=useState(false),[family,setFamily]=useState<Family|true|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const entries=s.events.filter(e=>!e.game_profile_id||e.game_profile_id===a.familyId);
  async function exportData(){setBusy(true);setError('');try{const {data,error}=await supabase.rpc('companion_export');if(error)throw error;const text=JSON.stringify(data,null,2),name='bdo-companion-'+new Date().toISOString().slice(0,10)+'.json';
    if(Capacitor.isNativePlatform()){const file=await Filesystem.writeFile({path:name,data:text,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:'Your BDO Companion export',files:[file.uri]});}
    else {const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}setMessage('Complete account export prepared.');
  }catch(e){setError(humanError(e));}finally{setBusy(false);}}
  async function linkGoogle(){setError('');setMessage('');if(isLocal){setMessage('Identity linking requires a configured Google OAuth client on Supabase.');return;}setBusy(true);try{const {data,error}=await supabase.auth.linkIdentity({provider:'google',options:{redirectTo:callbackUrl(),skipBrowserRedirect:Capacitor.isNativePlatform()}});if(error)throw error;if(data.url&&Capacitor.isNativePlatform())await Browser.open({url:data.url});}catch(e){setError(humanError(e));}finally{setBusy(false);}}
  async function linkDiscord(){setError('');setMessage('');if(isLocal){setMessage('Identity linking requires a configured Discord OAuth client on Supabase.');return;}setBusy(true);try{const {data,error}=await supabase.auth.linkIdentity({provider:'discord',options:{redirectTo:callbackUrl(),skipBrowserRedirect:Capacitor.isNativePlatform()}});if(error)throw error;if(data.url&&Capacitor.isNativePlatform())await Browser.open({url:data.url});}catch(e){setError(humanError(e));}finally{setBusy(false);}}
  return <><PageTitle eyebrow="THE STORY BEHIND YOUR PROGRESS" title={tab==='journal'?'Your adventurer’s journal.':'Make yourself at home.'} description={tab==='journal'?'Acquisitions, upgrades, and every step along the way.':'Your account, preferences, and family profiles.'}/>
    <div className="tabs section-tabs"><button className={tab==='journal'?'active':''} onClick={()=>setParams({tab:'journal'})}><BookOpen size={16}/>Journal</button><button className={tab==='settings'?'active':''} onClick={()=>setParams({tab:'settings'})}><Settings size={16}/>Settings</button></div>
    {message&&<p className="notice" role="status">{message}</p>}{error&&<p className="inline-error" role="alert">{error}</p>}
    {tab==='journal'?<Panel><div className="panel-heading"><div><h3>Your recorded history</h3><p className="muted">Latest 200 changes · export includes your full history</p></div><Button className="secondary" disabled={a.offline||!a.familyId} onClick={()=>setChoose(true)}><ArrowDownUp size={15}/>Record acquisition / correction</Button></div>
      {entries.length?<div className="journal-list">{entries.map(e=><button className="journal-entry" key={e.id} onClick={()=>setEvent(e)}><span className="journal-symbol"><BookOpen size={17}/></span><div><strong>{e.description}</strong><small>{new Date(e.created_at).toLocaleString()} · {e.kind.replaceAll('_',' ')}</small></div><ExternalLink size={15}/></button>)}</div>:<Empty title="Your first page is waiting">Saved changes will appear here with their before and after values.</Empty>}
      <p className="subtle-note">History is preserved. Correct a balance with an explicit adjustment; update equipment from Gear to record its new state.</p>
    </Panel>:<div className="settings-grid"><div>
      <Panel><div className="panel-heading"><h3>Your profile</h3><Settings size={17}/></div><SubmitForm onSubmit={async d=>{await a.save('profile_update',{display_name:str(d,'display_name'),timezone:str(d,'timezone'),preferences:{...s.profile.preferences,compact_numbers:d.has('compact_numbers'),reduce_motion:d.has('reduce_motion')}});}}>
        <Field label="Display name"><input name="display_name" required maxLength={60} defaultValue={s.profile.display_name}/></Field><Field label="Time zone"><input name="timezone" required maxLength={80} defaultValue={s.profile.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone}/></Field><Field label="Language"><select disabled aria-describedby="language-note"><option>English</option></select></Field><small id="language-note">More languages are planned.</small>
        <label className="check-row"><input type="checkbox" name="reduce_motion" defaultChecked={s.profile.preferences.reduce_motion===true}/>Reduce decorative motion</label>
        <Button loading={a.pending} disabled={a.offline} type="submit">Save preferences</Button></SubmitForm></Panel>
      <Panel><div className="panel-heading"><h3>Your families</h3><Button className="secondary small" disabled={a.offline||s.game_profiles.length>=2} onClick={()=>setFamily(true)}><Plus size={14}/>Add family</Button></div>{s.game_profiles.map(f=><div className="material-row" key={f.id}><div><strong>{f.family_name}</strong><small>PC · {f.region}</small></div><button className="icon-button" onClick={()=>setFamily(f)} disabled={a.offline} aria-label={'Edit '+f.family_name}><Pencil size={15}/></button></div>)}<p className="muted">One family per PC region. Add and manage characters on the Gear screen.</p></Panel>
    </div><div>
      <Panel><div className="panel-heading"><h3>Sign-in & security</h3><ShieldCheck size={18}/></div><p>{a.session?.user.email}</p><div className="material-chips">{a.session?.user.identities?.map(i=><Tag key={i.id}>{i.provider}</Tag>)}</div><p className="muted">Connect a verified Google or Discord identity to this account, so you can sign in with any of them. You will complete authentication with that provider before it is linked.</p><Button className="secondary full" loading={busy} disabled={a.offline||a.session?.user.identities?.some(i=>i.provider==='google')} onClick={()=>void linkGoogle()}>Link Google account</Button>
      <Button className="secondary full" loading={busy} disabled={a.offline||a.session?.user.identities?.some(i=>i.provider==='discord')} onClick={()=>void linkDiscord()}>Link Discord account</Button>
      <Button className="text-button" disabled={a.offline} onClick={async()=>{const {error}=await supabase.auth.resetPasswordForEmail(a.session!.user.email!,{redirectTo:callbackUrl('reset')});if(error)setError(humanError(error));else setMessage(isLocal?'Recovery link is in the local inbox.':'Check your email for the password recovery link.');}}>Send password reset email</Button><Button className="secondary full" onClick={()=>void a.signOut()}><LogOut size={15}/>Sign out of this device</Button></Panel>
      <Panel><h3>Your data belongs to you</h3><p className="muted">Export every family, character, item, resource, roadmap, reservation, claim, and journal entry.</p><Button className="secondary full" loading={busy} disabled={a.offline} onClick={()=>void exportData()}><Download size={16}/>Export all my data</Button><Link className="panel-link" to="/privacy">Privacy information <ExternalLink size={14}/></Link><Link className="text-link danger" to="/account-deletion"><Trash2 size={14}/>Delete my account</Link></Panel>
      {s.is_admin&&<Panel><Tag tone="gold">ADMINISTRATION</Tag><h3>Progression catalog</h3><p className="muted">Review sources, publish versions, and manage rollback.</p><Link className="button secondary" to="/admin">Open catalog administration</Link></Panel>}
    </div></div>}
    {event&&<Modal title="Progress detail" onClose={()=>setEvent(null)}><h3>{event.description}</h3><p className="muted">{new Date(event.created_at).toLocaleString()}</p><div className="history-values"><div><h4>Before</h4><pre>{JSON.stringify(event.before_state,null,2)??'No previous entry'}</pre></div><div><h4>After</h4><pre>{JSON.stringify(event.after_state,null,2)??'Entry removed'}</pre></div></div><small>Transaction {event.request_id}</small><p className="muted">Use “Record acquisition / correction” for resource adjustments. Edit Gear to correct equipment.</p></Modal>}
    {choose&&<Modal title="Choose a resource to adjust" onClose={()=>setChoose(false)}>{s.resources.filter(r=>r.game_profile_id===a.familyId).map(r=><button className="select-row" key={r.id} onClick={()=>{setChoose(false);setAdjust(r);}}>{r.name}<ArrowDownUp size={15}/></button>)}<Link to="/resources" onClick={()=>setChoose(false)}>Manage resources</Link></Modal>}
    {adjust&&<ResourceEditor resource={adjust} adjust onClose={()=>setAdjust(null)}/>}
    {family&&<FamilyEditor family={family===true?undefined:family} onClose={()=>setFamily(null)}/>}
  </>;
}
export function Privacy(){return <main className="standalone prose"><Link className="brand" to="/"><img src="/icon.svg" alt=""/><span>BDO <b>COMPANION</b></span></Link><p className="eyebrow">YOUR DATA, YOUR CHOICE</p><h1>Privacy information</h1><p>BDO Companion is an independent planning app for Black Desert Online PC NA/EU. It is not affiliated with Pearl Abyss and never asks for your game password.</p><h2>What is stored</h2><p>Your sign-in email and verified identities, display name, family profiles, characters, equipment, resources, roadmaps, reservations, family claims, preferences, and transaction history. Entered information is used to provide your companion and synchronize your devices.</p><h2>Where it is processed</h2><p>Supabase provides account authentication and database storage. Vercel serves the web app. When configured, Resend delivers verification and recovery emails. Google or Discord processes authentication if you choose to sign in or link an identity with either of them. This beta has no advertising, payments, or third-party marketing analytics.</p><h2>On this device</h2><p>The app stores your session and a private snapshot so you can view previous data offline. Offline data is read-only. Signing out or changing accounts clears cached player data. Avoid entering personal or sensitive information into game notes.</p><h2>Export and deletion</h2><p>Settings offers a full JSON export. You can delete your account from the app or the <Link to="/account-deletion">account deletion page</Link>. Deletion immediately blocks companion access and removes active player data, then removes the authentication account. Encrypted backups, when enabled for the invited beta, expire after seven days. Minimal deletion identifiers are retained so deleted data is removed again if a backup is restored.</p><h2>Retention and requests</h2><p>Player records remain until you delete the account. Operational logs are limited to diagnostics and do not intentionally include passwords, tokens, or exported player data. During testing, contact the person who invited you with privacy requests. The release operator and support contact must be supplied before public distribution.</p><p className="muted">Updated September 7, 2026 · Core beta</p><Link className="button secondary" to="/">Return to companion</Link></main>;}
export function DeleteAccount(){
  const a=useApp(),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');
  if(!a.authReady)return <main className="standalone">Loading account…</main>;
  if(!a.session&&!done)return <><div className="deletion-intro"><strong>Delete your BDO Companion account</strong><p>Sign in to confirm ownership. You will return here to review and delete your data.</p></div><Auth/></>;
  return <main className="standalone"><Link to="/" className="brand"><img src="/icon.svg" alt=""/><span>BDO <b>COMPANION</b></span></Link><h1>{done?'Your account was deleted.':'Delete your account'}</h1>{done?<><p>Your player data and sign-in account have been removed. Previous sessions can no longer access your data.</p><Link className="button secondary" to="/">Return to companion</Link></>:<><p>Signed in as <strong>{a.session?.user.email}</strong>.</p><p>This permanently removes every family, character, item, resource, roadmap, reservation, and journal entry in your account. Account removal cannot be undone.</p><p>Backups expire within seven days. A minimal deletion identifier is retained to prevent your data returning after a restore.</p><Link to="/more?tab=settings">Export your data first</Link><Field label="Type DELETE to confirm"><input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/></Field>
    <Button className="danger-button full" loading={busy} disabled={a.offline||confirm!=='DELETE'} onClick={async()=>{setBusy(true);setError('');try{const {data,error}=await supabase.functions.invoke('delete-account',{body:{confirmation:'DELETE'}});if(error)throw error;if(data?.status!=='deleted')throw Error('Player data was removed; sign-in account deletion is pending. Retry to finish.');setDone(true);await a.signOut();}catch(e){setError(humanError(e));}finally{setBusy(false);}}}><Trash2 size={16}/>Permanently delete my account</Button>{error&&<p className="inline-error" role="alert">{error}</p>}<Link to="/more?tab=settings">Cancel and return to settings</Link></>}</main>;
}
function CatalogEditor({catalog:initialCatalog,onClose}:{catalog:Catalog;onClose:()=>void}){
  const a=useApp(),[error,setError]=useState(''),[catalog,setCatalog]=useState(initialCatalog),[imported,setImported]=useState(false);
  return <Modal title={'Edit draft v'+catalog.version} onClose={onClose}><Button className="secondary" onClick={()=>{setCatalog({...initialCatalog,...ladderDraft,id:initialCatalog.id,version:initialCatalog.version} as Catalog);setImported(true);}}>Load supplied 70-step ladder into this draft</Button>{imported&&<div className="notice"><div><strong>Unreviewed draft loaded — save to persist</strong><ul>{ladderDraft.review_notes.map(note=><li key={note}>{note}</li>)}</ul></div></div>}<SubmitForm key={imported?"ladder":"existing"} onSubmit={async d=>{try{const content=JSON.parse(str(d,'content')),sources=JSON.parse(str(d,'sources'));if(await a.save('catalog_save',{id:catalog.id,title:str(d,'title'),content,sources,checked_at:str(d,'checked_at')||null,valid_until:str(d,'valid_until')||null,effective_patch:str(d,'effective_patch')}))onClose();}catch(e){setError(humanError(e));}}}>
    <Field label="Guide title"><input name="title" required maxLength={160} defaultValue={catalog.title}/></Field><Field label="Applicable patch and scope"><textarea name="effective_patch" required defaultValue={catalog.effective_patch}/></Field><div className="form-grid"><Field label="Verified on"><input type="date" name="checked_at" defaultValue={catalog.checked_at??''}/></Field><Field label="Review expires"><input type="date" name="valid_until" defaultValue={catalog.valid_until??''}/></Field></div>
    <Field label="Sources (JSON)" hint="At least two current references, including official NA/EU evidence."><textarea className="code-input" rows={7} name="sources" required defaultValue={JSON.stringify(catalog.sources,null,2)}/></Field><Field label="Catalog content (JSON)" hint="List prerequisites before the steps that depend on them."><textarea className="code-input" rows={16} name="content" required defaultValue={JSON.stringify(catalog.content,null,2)}/></Field>{error&&<p className="inline-error" role="alert">{error}</p>}<Button loading={a.pending} type="submit">Save draft</Button></SubmitForm></Modal>;
}
export function Admin(){
  const a=useApp(),s=a.snapshot!,[edit,setEdit]=useState<Catalog|null>(null),[transition,setTransition]=useState<{catalog:Catalog;status:string}|null>(null),[remove,setRemove]=useState<Catalog|null>(null);
  if(!s.is_admin)return <Empty title="Administrator access required">Catalog administration is restricted to designated reviewers.</Empty>;
  return <><PageTitle eyebrow="PROTECTED ADMINISTRATION" title="A guide worth trusting." description="Every published mechanic needs a version, scope, and current evidence."/><div className="notice">Publishing affects new goals. Existing plans stay pinned until their owner previews and confirms a migration.</div><div className="catalog-grid">{s.catalogs.map(c=><Panel key={c.id}><div className="panel-heading"><Tag tone={c.status==='published'?'green':'gold'}>{c.status}</Tag><strong>v{c.version}</strong></div><h2>{c.title}</h2><p className="muted">{c.effective_patch}</p><p>Verified {c.checked_at??'not yet'} · valid until {c.valid_until??'not set'}</p><p>{c.content.steps.length} milestones · {c.content.items.length} catalog item types</p>{c.sources.map(x=><div className="source-row" key={x.url}><External href={x.url}>{x.name}</External></div>)}<div className="actions wrap">
    <Button className="secondary small" loading={a.pending} disabled={a.offline} onClick={()=>void a.save('catalog_create',{id:c.id})}>Copy to new draft</Button>
    {c.status==='draft'&&<><Button className="small secondary" onClick={()=>setEdit(c)} disabled={a.offline}>Edit draft</Button><Button className="small" onClick={()=>setTransition({catalog:c,status:'review'})} disabled={a.offline}>Submit for review</Button><Button className="small text-button danger" onClick={()=>setRemove(c)} disabled={a.offline}><Trash2 size={14}/>Delete draft</Button></>}
    {c.status==='review'&&<><Button className="small secondary" onClick={()=>setTransition({catalog:c,status:'draft'})} disabled={a.offline}>Return to draft</Button><Button className="small" onClick={()=>setTransition({catalog:c,status:'published'})} disabled={a.offline}>Publish version</Button></>}
    {c.status==='retired'&&<Button className="small" onClick={()=>setTransition({catalog:c,status:'published'})} disabled={a.offline}>Roll back to version</Button>}
  </div></Panel>)}</div>{edit&&<CatalogEditor catalog={edit} onClose={()=>setEdit(null)}/>}
  {transition&&<Modal title={transition.status==='published'?'Confirm catalog publication':'Change review status'} onClose={()=>setTransition(null)}><p>Version {transition.catalog.version}: <strong>{transition.catalog.title}</strong></p><p>{transition.status==='published'?'I have checked the linked live sources, material quantities, prerequisites, regions, and distinct family reward claims. Publishing will replace the currently recommended version.':'Move this catalog to '+transition.status+'.'}</p><Button loading={a.pending} onClick={async()=>{if(await a.save('catalog_transition',{id:transition.catalog.id,status:transition.status}))setTransition(null);}}>Confirm {transition.status}</Button></Modal>}
  {remove&&<Modal title="Delete draft" onClose={()=>setRemove(null)}><p>Version {remove.version}: <strong>{remove.title}</strong></p><p>This permanently deletes the draft. It was never published, so no family's roadmap or equipment depends on it. This cannot be undone.</p><Button className="danger-button full" loading={a.pending} disabled={a.offline} onClick={async()=>{if(await a.save('catalog_delete',{id:remove.id}))setRemove(null);}}><Trash2 size={16}/>Permanently delete this draft</Button></Modal>}</>;
}
