import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {PageTitle,Panel,Field,Tag,External} from '../components/ui';
import data from '../data/gear-reference.json';
import grind from '../data/grind-reference.json';
import '../reference.css';

type Row={id:string;source_line:number;[key:string]:string|number|null};
type Block={type:string;text?:string;rows?:string[][]};
type GrindRow={source_line:number;[key:string]:string|number|null};
const rows=data.rows as Row[];
const labels:Record<string,string>={ap_min:'Weapon AP minimum',ap_max:'Weapon AP maximum',sheet_ap:'Sheet AP',sheet_dp:'Sheet DP',accuracy:'Accuracy',monster_ap:'Extra AP against monsters',monster_dr:'Monster damage reduction',evasion:'Visible evasion',hidden_evasion:'Hidden evasion',damage_reduction:'Visible damage reduction',hidden_damage_reduction:'Hidden damage reduction',max_hp:'Maximum HP',max_stamina:'Maximum stamina',weight_lt:'Weight (LT)',delta_ap_min:'AP minimum increase',delta_ap_max:'AP maximum increase',delta_sheet_ap:'Sheet AP increase',delta_sheet_dp:'Sheet DP increase'};
const groupKey=(r:Row)=>[r.item,r.variant,r.slot].join(' · ');
const silver=(v:string|number|null)=>v===null?null:Number(v).toLocaleString('en-US');
const findBracket=(type:string,value:number)=>(grind.brackets as GrindRow[]).find(r=>r.record_type===type&&Number(r.min_sheet)<=value&&(r.max_sheet===null||value<=Number(r.max_sheet)));
const evalFormula=(formula:string|number|null,sheet_ap:number)=>{if(typeof formula!=='string')return null;try{return new Function('sheet_ap','return '+formula)(sheet_ap) as number;}catch{return null;}};
export function Reference(){
  const [tab,setTab]=useState('stats'),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[selected,setSelected]=useState(groupKey(rows[0])),[level,setLevel]=useState('+0'),[compare,setCompare]=useState('');
  const [myAp,setMyAp]=useState(''),[myDp,setMyDp]=useState(''),[zoneRegion,setZoneRegion]=useState('all'),[costCategory,setCostCategory]=useState('all'),[costGroup,setCostGroup]=useState('');
  const apVal=Number(myAp),dpVal=Number(myDp),hasAp=myAp!==''&&!Number.isNaN(apVal),hasDp=myDp!==''&&!Number.isNaN(dpVal);
  const apBracket=hasAp?findBracket('AP_BRACKET',apVal):undefined,monsterApRow=hasAp?findBracket('MONSTER_AP_SCALING',apVal):undefined;
  const monsterAp=monsterApRow?evalFormula(monsterApRow.formula,apVal):null;
  const dpRateBracket=hasDp?findBracket('DP_DR_RATE_BRACKET',dpVal):undefined,dpFlatBracket=hasDp?findBracket('DP_FLAT_DR_BRACKET',dpVal):undefined;
  const zoneRegions=useMemo(()=>[...new Set((grind.zones as GrindRow[]).map(z=>String(z.region)))],[]);
  const filteredZones=useMemo(()=>(grind.zones as GrindRow[]).filter(z=>zoneRegion==='all'||z.region===zoneRegion),[zoneRegion]);
  const costCategories=useMemo(()=>[...new Set((grind.costs as GrindRow[]).map(c=>String(c.category)))],[]);
  const costGroups=useMemo(()=>[...new Set((grind.costs as GrindRow[]).filter(c=>costCategory==='all'||c.category===costCategory).map(c=>String(c.item_group)))],[costCategory]);
  const activeCostGroup=costGroups.includes(costGroup)?costGroup:costGroups[0];
  const costLadder=useMemo(()=>(grind.costs as GrindRow[]).filter(c=>c.item_group===activeCostGroup),[activeCostGroup]);
  const groups=useMemo(()=>[...new Set(rows.filter(r=>(category==='all'||r.category===category)&&groupKey(r).toLowerCase().includes(search.toLowerCase())).map(groupKey))],[search,category]);
  const active=groups.includes(selected)?selected:groups[0],ladder=rows.filter(r=>groupKey(r)===active),row=ladder.find(r=>r.enhancement===level)??ladder[0],other=ladder.find(r=>r.enhancement===compare);
  const issues=row?data.issues.filter(i=>i.id===row.id):[];
  return <><PageTitle eyebrow="PC NA/EU · COMMUNITY REFERENCE" title="Plan beyond your next upgrade." description="Your imported September 2026 gear tables and PvE progression guide."/>
    <Link className="text-link" to="/gear">← Back to your equipment</Link>
    <p className="notice">Imported reference · pending review. These values are not used for automated recommendations or your equipment totals. Blank values mean unknown or not supplied, never zero.</p>
    <div className="tabs section-tabs"><button className={tab==='stats'?'active':''} onClick={()=>setTab('stats')}>Gear stats · {rows.length}</button><button className={tab==='guide'?'active':''} onClick={()=>setTab('guide')}>PvE progression guide</button><button className={tab==='grind'?'active':''} onClick={()=>setTab('grind')}>Grind zones & costs · {grind.zones.length}</button></div>
    {tab==='grind'?<><Panel><h3>Find your bracket</h3><p className="subtle-note">Displayed AP/DP bracket bonuses and monster-facing scaling, from the supplied {grind.imported_at} bracket tables. Enter your own sheet values to see which brackets apply.</p>
    <div className="reference-filters"><Field label="Your sheet AP"><input type="number" value={myAp} onChange={e=>setMyAp(e.target.value)} placeholder="e.g. 320"/></Field><Field label="Your sheet DP"><input type="number" value={myDp} onChange={e=>setMyDp(e.target.value)} placeholder="e.g. 420"/></Field></div>
    {(hasAp||hasDp)&&<dl className="bracket-result">
      {hasAp&&<div><dt>AP bracket bonus</dt><dd>{apBracket?`+${apBracket.bonus_value} AP`:'Below 100 AP'}</dd></div>}
      {hasAp&&<div><dt>Extra AP vs. monsters</dt><dd>{monsterAp!==null?`+${monsterAp} Monster AP`:'Below 310 AP'}</dd></div>}
      {hasDp&&<div><dt>Damage reduction rate</dt><dd>{dpRateBracket?`+${dpRateBracket.bonus_value}% DR`:'Below 203 DP'}</dd></div>}
      {hasDp&&<div><dt>Flat damage reduction</dt><dd>{dpFlatBracket?`+${dpFlatBracket.bonus_value} flat DR`:'Below 253 DP'}</dd></div>}
    </dl>}
    <p className="subtle-note">Monster AP scaling: {(grind.brackets as GrindRow[]).filter(b=>b.record_type==='MONSTER_AP_SCALING').map(b=>`${b.min_sheet}${b.max_sheet?`–${b.max_sheet}`:'+'} AP: ${b.formula}`).join('; ')}.</p>
    <External href={grind.bracket_source_urls[0]}>Supplied source</External></Panel>
    <Panel><h3>Target zone requirements</h3><p className="subtle-note">Recommended sheet/total AP and DP per grind zone, from the supplied {grind.imported_at} zone tables. Blank values were not safely verified and are never treated as zero.</p>
    <Field label="Region"><select value={zoneRegion} onChange={e=>setZoneRegion(e.target.value)}><option value="all">All regions</option>{zoneRegions.map(r=><option key={r}>{r}</option>)}</select></Field>
    <div className="reference-table" tabIndex={0} role="region" aria-label="Grind zone requirements"><table><thead><tr><th scope="col">Zone</th><th scope="col">Party</th><th scope="col">Sheet AP</th><th scope="col">Sheet DP</th><th scope="col">Total AP</th><th scope="col">Total DP</th><th scope="col">Effective AP cap</th><th scope="col">Meets your AP/DP?</th></tr></thead><tbody>{filteredZones.map(z=><tr key={String(z.region)+String(z.zone)}><td>{z.zone}<br/><small className="muted">{z.region}</small></td><td>{z.party_size}</td><td>{z.recommended_sheet_ap??'Unknown'}</td><td>{z.recommended_sheet_dp??'Unknown'}</td><td>{z.recommended_total_ap??'Unknown'}</td><td>{z.recommended_total_dp??'Unknown'}</td><td>{z.effective_ap_cap_total??'Unknown'}</td><td>{hasAp&&hasDp&&z.recommended_sheet_ap!==null&&z.recommended_sheet_dp!==null?(apVal>=Number(z.recommended_sheet_ap)&&dpVal>=Number(z.recommended_sheet_dp)?<Tag tone="gold">Ready</Tag>:<Tag>Not yet</Tag>):'—'}</td></tr>)}</tbody></table></div></Panel>
    <Panel><h3>Upgrade silver costs</h3><p className="subtle-note">BDO Workshop expected one-level enhancement costs and market anchors, snapshotted {grind.imported_at}. Treat these as a snapshot, not a timeless fact — market inputs and failstack strategy change. Blank costs mean the concept doesn't apply (e.g. Apeiron enhancement consumes another base item rather than costing silver directly).</p>
    <div className="reference-filters"><Field label="Category"><select value={costCategory} onChange={e=>{setCostCategory(e.target.value);setCostGroup('');}}><option value="all">All categories</option>{costCategories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Item group"><select value={activeCostGroup} onChange={e=>setCostGroup(e.target.value)}>{costGroups.map(g=><option key={g}>{g}</option>)}</select></Field></div>
    <div className="reference-table" tabIndex={0} role="region" aria-label="Upgrade silver costs"><table><thead><tr><th scope="col">From</th><th scope="col">To</th><th scope="col">Cron stones</th><th scope="col">Expected one-level cost</th><th scope="col">Market anchor</th><th scope="col">Confidence</th></tr></thead><tbody>{costLadder.map(c=><tr key={c.id as string}><td>{c.from_level}</td><td>{c.to_level}</td><td>{c.cron_stones_per_attempt??'—'}</td><td>{silver(c.expected_one_level_cost_silver)?`${silver(c.expected_one_level_cost_silver)} silver`:c.cost_model}</td><td>{silver(c.market_upgrade_anchor_silver)?`${silver(c.market_upgrade_anchor_silver)} silver`:'—'}</td><td><Tag>{c.cost_confidence}</Tag></td></tr>)}</tbody></table></div>
    {costLadder[0]&&<><p className="subtle-note">{costLadder[0].snapshot_notes}</p><External href={grind.sources[costLadder[0].source_id as keyof typeof grind.sources]}>Supplied source</External></>}</Panel>
    </>:tab==='stats'?<><Panel><div className="reference-filters"><Field label="Search equipment"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Sovereign, Edana, Kharazad…"/></Field><Field label="Category"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(rows.map(r=>String(r.category)))].map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select></Field></div>
    {groups.length?<><Field label="Item and variant"><select value={active} onChange={e=>{setSelected(e.target.value);setLevel('+0');setCompare('');}}>{groups.map(g=><option key={g}>{g}</option>)}</select></Field><div className="reference-filters"><Field label="Enhancement"><select value={String(row.enhancement)} onChange={e=>setLevel(e.target.value)}>{ladder.map(r=><option key={r.id}>{r.enhancement}</option>)}</select></Field><Field label="Compare enhancement"><select value={other?compare:''} onChange={e=>setCompare(e.target.value)}><option value="">No comparison</option>{ladder.map(r=><option key={r.id}>{r.enhancement}</option>)}</select></Field></div>
    <h2>{row.item} <Tag>{row.enhancement}</Tag></h2>{issues.map(i=><p className="notice" key={i.id}>Review flag: {i.reason}</p>)}
    <div className="reference-table" tabIndex={0} role="region" aria-label="Gear statistics"><table><thead><tr><th scope="col">Stat</th><th scope="col">{row.enhancement}</th>{other&&<><th scope="col">{other.enhancement}</th><th scope="col">Change</th></>}</tr></thead><tbody>{Object.entries(labels).map(([key,label])=><tr key={key}><th scope="row">{label}</th><td>{row[key]??'Unknown'}</td>{other&&<><td>{other[key]??'Unknown'}</td><td>{row[key]===null||other[key]===null?'Unknown':String(Number(other[key])-Number(row[key]))}</td></>}</tr>)}</tbody></table></div>
    {row.notes&&<p className="subtle-note">{row.notes}</p>}<p className="subtle-note">Set effects and reform bonuses are separate. Monster AP is not sheet AP; monster damage reduction is not sheet DP.</p><External href={data.sources[row.source_id as keyof typeof data.sources]}>Supplied source</External><small className="muted"> · Imported file line {row.source_line} · Unreviewed</small></>:<p role="status">No equipment matches your filters.</p>}</Panel><Panel><h3>Import review</h3><p>{data.issues.length} rows have arithmetic flags for review. Source dates and the document’s verification claims are preserved as supplied; they do not replace an app catalog review.</p><details><summary>Show flagged rows</summary><ul>{data.issues.map(i=><li key={i.id}>{i.id.replaceAll(':',' · ')} — line {i.line}</li>)}</ul></details></Panel></>:<Panel><p className="subtle-note">User-supplied guide, dated 8 September 2026. Progression priorities are general guidance; costs, class, eligibility and grind-zone requirements can change their order. No resources are spent by reading this guide.</p>{data.sections.map(section=><details className="reference-section" key={section.title}><summary>{section.title}</summary>{(section.blocks as Block[]).map((block,i)=>block.type==='table'?<div key={i} className="reference-table" tabIndex={0} role="region" aria-label={section.title+' table'}><table><tbody>{block.rows?.map((cells,j)=><tr key={j}>{cells.map((cell,k)=>j===0?<th key={k} scope="col">{cell}</th>:<td key={k}>{cell}</td>)}</tr>)}</tbody></table></div>:<p key={i}>{block.text}</p>)}</details>)}</Panel>}
  </>;
}
