import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {PageTitle,Panel,Field,Tag,External} from '../components/ui';
import data from '../data/gear-reference.json';
import '../reference.css';

type Row={id:string;source_line:number;[key:string]:string|number|null};
type Block={type:string;text?:string;rows?:string[][]};
const rows=data.rows as Row[];
const labels:Record<string,string>={ap_min:'Weapon AP minimum',ap_max:'Weapon AP maximum',sheet_ap:'Sheet AP',sheet_dp:'Sheet DP',accuracy:'Accuracy',monster_ap:'Extra AP against monsters',monster_dr:'Monster damage reduction',evasion:'Visible evasion',hidden_evasion:'Hidden evasion',damage_reduction:'Visible damage reduction',hidden_damage_reduction:'Hidden damage reduction',max_hp:'Maximum HP',max_stamina:'Maximum stamina',weight_lt:'Weight (LT)',delta_ap_min:'AP minimum increase',delta_ap_max:'AP maximum increase',delta_sheet_ap:'Sheet AP increase',delta_sheet_dp:'Sheet DP increase'};
const groupKey=(r:Row)=>[r.item,r.variant,r.slot].join(' · ');
export function Reference(){
  const [tab,setTab]=useState('stats'),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[selected,setSelected]=useState(groupKey(rows[0])),[level,setLevel]=useState('+0'),[compare,setCompare]=useState('');
  const groups=useMemo(()=>[...new Set(rows.filter(r=>(category==='all'||r.category===category)&&groupKey(r).toLowerCase().includes(search.toLowerCase())).map(groupKey))],[search,category]);
  const active=groups.includes(selected)?selected:groups[0],ladder=rows.filter(r=>groupKey(r)===active),row=ladder.find(r=>r.enhancement===level)??ladder[0],other=ladder.find(r=>r.enhancement===compare);
  const issues=row?data.issues.filter(i=>i.id===row.id):[];
  return <><PageTitle eyebrow="PC NA/EU · COMMUNITY REFERENCE" title="Plan beyond your next upgrade." description="Your imported September 2026 gear tables and PvE progression guide."/>
    <Link className="text-link" to="/gear">← Back to your equipment</Link>
    <p className="notice">Imported reference · pending review. These values are not used for automated recommendations or your equipment totals. Blank values mean unknown or not supplied, never zero.</p>
    <div className="tabs section-tabs"><button className={tab==='stats'?'active':''} onClick={()=>setTab('stats')}>Gear stats · {rows.length}</button><button className={tab==='guide'?'active':''} onClick={()=>setTab('guide')}>PvE progression guide</button></div>
    {tab==='stats'?<><Panel><div className="reference-filters"><Field label="Search equipment"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Sovereign, Edana, Kharazad…"/></Field><Field label="Category"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(rows.map(r=>String(r.category)))].map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select></Field></div>
    {groups.length?<><Field label="Item and variant"><select value={active} onChange={e=>{setSelected(e.target.value);setLevel('+0');setCompare('');}}>{groups.map(g=><option key={g}>{g}</option>)}</select></Field><div className="reference-filters"><Field label="Enhancement"><select value={String(row.enhancement)} onChange={e=>setLevel(e.target.value)}>{ladder.map(r=><option key={r.id}>{r.enhancement}</option>)}</select></Field><Field label="Compare enhancement"><select value={other?compare:''} onChange={e=>setCompare(e.target.value)}><option value="">No comparison</option>{ladder.map(r=><option key={r.id}>{r.enhancement}</option>)}</select></Field></div>
    <h2>{row.item} <Tag>{row.enhancement}</Tag></h2>{issues.map(i=><p className="notice" key={i.id}>Review flag: {i.reason}</p>)}
    <div className="reference-table" tabIndex={0} role="region" aria-label="Gear statistics"><table><thead><tr><th scope="col">Stat</th><th scope="col">{row.enhancement}</th>{other&&<><th scope="col">{other.enhancement}</th><th scope="col">Change</th></>}</tr></thead><tbody>{Object.entries(labels).map(([key,label])=><tr key={key}><th scope="row">{label}</th><td>{row[key]??'Unknown'}</td>{other&&<><td>{other[key]??'Unknown'}</td><td>{row[key]===null||other[key]===null?'Unknown':String(Number(other[key])-Number(row[key]))}</td></>}</tr>)}</tbody></table></div>
    {row.notes&&<p className="subtle-note">{row.notes}</p>}<p className="subtle-note">Set effects and reform bonuses are separate. Monster AP is not sheet AP; monster damage reduction is not sheet DP.</p><External href={data.sources[row.source_id as keyof typeof data.sources]}>Supplied source</External><small className="muted"> · Imported file line {row.source_line} · Unreviewed</small></>:<p role="status">No equipment matches your filters.</p>}</Panel><Panel><h3>Import review</h3><p>{data.issues.length} rows have arithmetic flags for review. Source dates and the document’s verification claims are preserved as supplied; they do not replace an app catalog review.</p><details><summary>Show flagged rows</summary><ul>{data.issues.map(i=><li key={i.id}>{i.id.replaceAll(':',' · ')} — line {i.line}</li>)}</ul></details></Panel></>:<Panel><p className="subtle-note">User-supplied guide, dated 8 September 2026. Progression priorities are general guidance; costs, class, eligibility and grind-zone requirements can change their order. No resources are spent by reading this guide.</p>{data.sections.map(section=><details className="reference-section" key={section.title}><summary>{section.title}</summary>{(section.blocks as Block[]).map((block,i)=>block.type==='table'?<div key={i} className="reference-table" tabIndex={0} role="region" aria-label={section.title+' table'}><table><tbody>{block.rows?.map((cells,j)=><tr key={j}>{cells.map((cell,k)=>j===0?<th key={k} scope="col">{cell}</th>:<td key={k}>{cell}</td>)}</tr>)}</tbody></table></div>:<p key={i}>{block.text}</p>)}</details>)}</Panel>}
  </>;
}
