import type {Character,Equipment,Family} from '../domain/types';
import {slots,enhancementLabel} from '../domain/types';
import {useState} from 'react';
import {Button,Field,Modal,SubmitForm,str} from './ui';
import {useApp} from '../lib/AppContext';
export function FamilyEditor({family,onClose}:{family?:Family;onClose:()=>void}){
  const {save,pending,offline}=useApp();
  return <Modal title={family?'Edit family':'Create a family profile'} onClose={onClose}><SubmitForm onSubmit={async d=>{if(await save(family?'family_update':'family_create',{id:family?.id,family_name:str(d,'family_name'),region:str(d,'region')}))onClose();}}>
    <p className="muted">Characters and shared resources stay within their game region.</p><Field label="Family name"><input name="family_name" defaultValue={family?.family_name} required maxLength={60}/></Field><Field label="PC region"><select name="region" defaultValue={family?.region??'EU'} disabled={!!family}><option>EU</option><option>NA</option></select></Field><Button type="submit" loading={pending} disabled={offline}>Save family</Button></SubmitForm></Modal>;
}
export function CharacterEditor({character,onClose}:{character?:Character;onClose:()=>void}){
  const {save,pending,offline,familyId}=useApp();
  return <Modal title={character?'Edit character':'Add a character'} onClose={onClose}><SubmitForm onSubmit={async d=>{if(await save('character_save',{id:character?.id,game_profile_id:familyId,name:str(d,'name'),class_name:str(d,'class_name'),level:Number(str(d,'level')),playstyle:str(d,'playstyle'),notes:str(d,'notes')}))onClose();}}>
    <Field label="Character name"><input name="name" required maxLength={60} defaultValue={character?.name}/></Field><div className="form-grid"><Field label="Class"><input name="class_name" placeholder="e.g. Scholar" required maxLength={60} defaultValue={character?.class_name}/></Field><Field label="Level"><input name="level" type="number" min={1} max={100} required defaultValue={character?.level??60}/></Field></div><Field label="Playstyle"><select name="playstyle" defaultValue={character?.playstyle??'PvE'}><option>PvE</option><option>PvP</option><option>Life skills</option><option>Mixed</option></select></Field><Field label="Notes"><textarea name="notes" maxLength={2000} defaultValue={character?.notes}/></Field><Button loading={pending} disabled={offline} type="submit">Save character</Button></SubmitForm></Modal>;
}
export function GearEditor({equipment,initialSlot,onRemove,onClose}:{equipment?:Equipment;initialSlot?:string;onRemove?:()=>void;onClose:()=>void}){
  const {snapshot:s,save,pending,offline,familyId,characterId}=useApp();const catalog=s?.catalogs.find(c=>equipment?.catalog_version_id?c.id===equipment.catalog_version_id:c.status==='published');
  const [itemKey,setItemKey]=useState(equipment?.item_key??''),[assignment,setAssignment]=useState(equipment?equipment.character_id??'':characterId),[level,setLevel]=useState(equipment?.enhancement??20);
  const [preview,setPreview]=useState<{data:Record<string,unknown>;revision:number;rows:{name:string;before:string;spent:string;after:string;available:string}[]}|null>(null);
  const resources=s?.resources.filter(r=>r.game_profile_id===familyId)??[];
  const item=catalog?.content.items.find(i=>i.key===itemKey),compatible=Object.entries(slots).filter(([key])=>!item||item.slots.includes(key));
  if(preview)return <Modal title="Confirm equipment upgrade" onClose={onClose}><p>Update {equipment?.name} to {String(preview.data.name)} · {enhancementLabel(Number(preview.data.enhancement))}. The same owned item is updated.</p><p>These are your manually entered costs, not a verified recipe.</p>{preview.rows.map(r=><p key={r.name}><strong>{r.name}</strong>: {r.before} owned − {r.spent} spent = {r.after} remaining. Available before spending: {r.available}.</p>)}{preview.rows.some(r=>BigInt(r.spent)>BigInt(r.available))&&<p role="alert">Release reservations or add resources before recording this upgrade.</p>}<Button loading={pending} disabled={offline||preview.rows.some(r=>BigInt(r.spent)>BigInt(r.available))} onClick={async()=>{if(await save('gear_save',preview.data,preview.revision))onClose();}}>Confirm upgrade and deduct resources</Button><Button className="secondary" disabled={pending} onClick={()=>setPreview(null)}>Back to equipment</Button></Modal>;
  return <Modal title={equipment?'Edit equipment':'Add equipment'} onClose={onClose}><SubmitForm onSubmit={async d=>{
    const data={id:equipment?.id,game_profile_id:familyId,character_id:assignment||null,slot:assignment?str(d,'slot'):null,name:item?.name??str(d,'name'),catalog_version_id:item?catalog?.id:null,item_key:item?.key??null,enhancement:level,reform:item?0:Number(str(d,'reform')),caphras:item?0:Number(str(d,'caphras')),notes:str(d,'notes')};
    const costs=resources.map(r=>({resource_id:r.id,quantity:str(d,'cost:'+r.id)})).filter(c=>c.quantity&&BigInt(c.quantity)>0n);
    if(equipment&&costs.length&&s){setPreview({data:{...data,costs},revision:s.profile.revision,rows:costs.map(c=>{const r=resources.find(r=>r.id===c.resource_id)!;const reserved=s.allocations.filter(x=>x.resource_id===r.id).reduce((sum,x)=>sum+BigInt(x.quantity),0n);return {name:r.name,before:r.quantity,spent:c.quantity,after:(BigInt(r.quantity)-BigInt(c.quantity)).toString(),available:(BigInt(r.quantity)-reserved).toString()};})});return;}
    if(await save('gear_save',data))onClose();
  }}>
    <Field label="Item source"><select value={itemKey} onChange={e=>{setItemKey(e.target.value);if(e.target.value)setLevel(20);}}><option value="">Custom item · manually entered</option>{catalog?.content.items.map(i=><option key={i.key} value={i.key}>{i.name}</option>)}</select></Field>
    {!item&&<Field label="Item name" hint="Custom items are saved as your entries; no unverified stats are calculated."><input name="name" required maxLength={120} defaultValue={equipment?.name}/></Field>}
    <div className="form-grid"><Field label="Enhancement"><select value={level} onChange={e=>setLevel(Number(e.target.value))}>{(item?.enhancements??Array.from({length:26},(_,i)=>i)).map(i=><option key={i} value={i}>{enhancementLabel(i)}</option>)}</select></Field><Field label="Assign to"><select value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="">Family inventory</option>{s?.characters.filter(c=>c.game_profile_id===familyId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field></div>
    {assignment&&<Field label="Equipment slot"><select name="slot" key={itemKey} defaultValue={equipment?.slot??(compatible.some(([key])=>key===initialSlot)?initialSlot:compatible[0]?.[0])}>{compatible.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>}
    {!item&&<div className="form-grid"><Field label="Reform level"><input name="reform" type="number" min={0} max={5} defaultValue={equipment?.reform??0}/></Field><Field label="Caphras level"><input name="caphras" type="number" min={0} max={20} defaultValue={equipment?.caphras??0}/></Field></div>}
    <Field label="Notes"><textarea name="notes" maxLength={2000} defaultValue={equipment?.notes}/></Field>{equipment&&s?.capabilities?.includes('equipment_costs_v1')&&<details><summary>Record upgrade costs</summary><p>Enter what you actually spent. Blank costs only update the equipment record. Any deduction requires confirmation.</p>{resources.map(r=><Field key={r.id} label={'Spend '+r.name}><input name={'cost:'+r.id} inputMode="numeric" pattern="[0-9]{1,19}" maxLength={19} placeholder="0"/></Field>)}</details>}<Button type="submit" loading={pending} disabled={offline}>Save equipment</Button>{equipment&&onRemove&&<Button type="button" className="text-button danger" disabled={offline||pending} onClick={onRemove}>Remove this equipment</Button>}</SubmitForm></Modal>;
}
